name: Notify Google Chat on Push

# Trigger on push to any branch
on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Google Chat
        if: ${{ github.event_name == 'push' }}
        env:
          WEBHOOK_URL: ${{ secrets.GCHAT_WEBHOOK }}  # Add your Google Chat webhook as secret
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${GITHUB_REF##*/}"   # Extract branch from ref
          ACTOR="${{ github.actor }}"
          COUNT=$(jq '.commits | length' "$GITHUB_EVENT_PATH")

          # Get last 5 commits
          COMMITS_HTML=$(
            jq -r '[.commits[0:5][] | 
              "• " + (.message | gsub("\\r?\\n"; " ")) + 
              " (by " + .author.username + ")" +
              " - Files changed: " + ((.added + .modified + .removed) | join(", "))
            ] | join("<br>")' "$GITHUB_EVENT_PATH"
          )

          # Build Google Chat JSON card
          jq -n \
            --arg repo "$REPO" \
            --arg branch "$BRANCH" \
            --arg actor "$ACTOR" \
            --arg count "$COUNT" \
            --arg commits "$COMMITS_HTML" \
            '{
              cardsV2: [{
                cardId: "push-card",
                card: {
                  header: {
                    title: ("🚀 New push to branch " + $branch),
                    subtitle: $repo
                  },
                  sections: [
                    { widgets: [
                      { textParagraph: { text: ("<b>Repository:</b> " + $repo + "<br><b>Branch:</b> " + $branch + "<br><b>Pusher:</b> " + $actor + "<br><b>Commit count:</b> " + $count) } }
                    ]},
                    { header: "Commits",
                      widgets: [
                        { textParagraph: { text: ($commits // "No commits found") } }
                      ]
                    }
                  ]
                }
              }]
            }' \
          | curl -s -X POST -H 'Content-Type: application/json; charset=UTF-8' -d @- "$WEBHOOK_URL"
