name: Notify Google Chat on Push

on:
  push:
    branches:
      - kzt
      - main  # add main branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Google Chat
        env:
          GCHAT_WEBHOOK: ${{ secrets.GCHAT_WEBHOOK }}
        run: |
          # Committer who pushed
          COMMITTER="${{ github.actor }}"
          
          # Extract branch name from ref (refs/heads/branch -> branch)
          BRANCH="${GITHUB_REF#refs/heads/}"
          
          # Repository name
          REPO="${{ github.repository }}"
          
          # Message to send
          MESSAGE="${COMMITTER} pushed to branch ${BRANCH} in repository ${REPO}"
          
          # Send message via curl
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${MESSAGE}\"}" \
            "$GCHAT_WEBHOOK"
